version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: temp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}